---
title: "Dad Questions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(rvest)
library(here)
library(uwot)
library(dbscan)
library(plotly)
```

## Pull data from WTE.com forum including archives

```{r download-titles, eval=FALSE}

scrape_titles <- function(page = 1) {
    
    url <- if_else(page == 1, 
                   "https://community.whattoexpect.com/forums/dads-corner.html",
                   paste0("https://community.whattoexpect.com/forums/dads-corner.html", 
                          "?page=", page))
    
    dads_corner <- read_html(url)
    
    tibble(titles = dads_corner %>% 
         html_nodes(".group-discussions__list__item__title span") %>%
         html_text(),
       comment_count = dads_corner %>% 
         html_nodes(".group-discussions__list__item__block") %>% 
         html_node(".group-discussions__list__item__comments span") %>%
         html_text()) %>% 
      mutate(comment_count = replace_na(as.numeric(str_remove(comment_count, " Comments?")), 0)) 
}

dads_titles <- vector("list", 17)

for (i in seq_along(dads_titles)) {
    print(i)
    Sys.sleep(5)
    dads_titles[[i]] <- scrape_titles(page = i)
    
    sprintf("Page %s done", i)
}

titles <- enframe(dads_titles, name = "page", value = "titles") %>% 
    unnest(cols = c("titles"))

write_csv(titles, here("data/titles.csv"))
```


```{r download-archive, eval=FALSE}

scrape_archive <- function(page = 1) {
    
    url <- if_else(page == 1, 
                   "https://community.whattoexpect.com/forums/dads-corner/archives.html",
                   paste0("https://community.whattoexpect.com/forums/dads-corner/archives.html", 
                          "?page=", page))
    
    dads_corner <- read_html(url)
    
    tibble(titles = dads_corner %>% 
         html_nodes(".group-discussions__list__item__title span") %>%
         html_text(),
       comment_count = dads_corner %>% 
         html_nodes(".group-discussions__list__item__block") %>% 
         html_node(".group-discussions__list__item__comments span") %>%
         html_text()) %>% 
      mutate(comment_count = replace_na(as.numeric(str_remove(comment_count, " Comments?")), 0)) 
}

archive_titles <- vector("list", 6)

for (i in seq_along(archive_titles)) {
    print(i)
    Sys.sleep(5)
    archive_titles[[i]] <- scrape_archive(page = i)
    
    sprintf("Page %s done", i)
}

archive <- enframe(archive_titles, name = "page", value = "titles") %>% 
    unnest(cols = c("titles"))

write_csv(archive, here("data/archive.csv"))
```

```{r all-titles, eval=FALSE}
all_titles <- 
  titles %>% 
  mutate(source = "dads_corner") %>% 
  bind_rows(
    archive %>% 
      mutate(source = "archive"))

write_csv(all_titles, here("data/all_titles.csv"))
```


```{r titles}
titles <- read_csv(here("data/all_titles.csv"))
embeddings <- read_csv(here("data/embeddings.csv"), col_names = FALSE)
```


## UMAP

```{r}
dad_umap <- umap(embeddings,
                 n_neighbors = 30,
                 n_components = 10,
                 min_dist = 0,
                 metric = "euclidean")
```

### Plot UMAP results

```{r}
as_tibble(dad_umap) %>% 
  bind_cols(titles) %>% 
  ggplot(aes(x = V1, y = V2, label = titles)) +
  geom_point()

ggplotly()
```

## Clustering

```{r}
clusts <- hdbscan(dad_umap,
        minPts = 15)
```

```{r dad-clusts}
dads_clusts <- 
  as_tibble(dad_umap) %>% 
  bind_cols(titles) %>% 
  mutate(cluster = clusts$cluster,
         clust_prop = clusts$membership_prob) %>% 
  dplyr::group_by(cluster) %>% 
  mutate(post_count = n(),
         tot_comments = sum(comment_count),
         comment_ratio = tot_comments / post_count) %>% 
  ungroup()
```

### Plot clusters

```{r}
dads_clusts %>% 
  ggplot(aes(x = V1, y = V2, label = titles, 
             label2 = post_count, label3 = tot_comments, label4 = comment_ratio)) +
  geom_point(aes(color = factor(cluster)))

ggplotly()
```

### List clusters

```{r}
dads_clusts %>% 
  group_by(cluster) %>% 
  arrange(desc(clust_prop)) %>% 
  slice(1:5) %>% 
  ungroup() %>% 
  select(-contains("V")) %>% 
  arrange(desc(tot_comments), cluster)
```


## Hyperparameter search

```{r}
umap_func <- function(df) {
  as_tibble(umap(embeddings, n_neighbors = df$nn, min_dist = df$md))
}
```


```{r}
umap_results <- expand.grid(nn = c(10, 15, 30, 50),
            md = c(0, .001, .01, .1)) %>% 
  mutate(trial = row_number()) %>% 
  group_by(trial) %>% 
  nest() %>% 
  mutate(umap = map(data, umap_func))
```

```{r}
umap_results %>% 
  mutate(titles = map(trial, ~as_tibble(titles))) %>% 
  unnest() %>% 
  ungroup() %>% 
  ggplot(aes(x = V1, y = V2, label = titles)) +
  geom_point(alpha = .1) +
  facet_wrap(nn ~ md, scales = "free")
```

